[mgr]
sort_by = "natural"
sort_dir_first = true
sort_sensitive = true
sort_translit = true

[open]
prepend_rules = [
  { mime = "image/*", use = "imv" },
  { mime = "video/*", use = "mpv_player" },
]

[opener]
imv = [{ desc = "Open with imv", orphan = true, run = "imv \"$@\"" }]
mpv_player = [{ desc = "Play with mpv", orphan = true, run = "mpv \"$@\"" }]

[preview]
wrap = "yes"
tab_size = 2
